services:
  strongswan:
    image: strongswan
    build:
      context: .
      dockerfile: Dockerfile
    cap_add:
      - NET_ADMIN
    ports:
      - "500:500/udp"
      - "4500:4500/udp"
    volumes:
      - ./ca-cert.pem:/etc/swanctl/x509ca/ca-cert.pem
      - ./server-cert.pem:/etc/swanctl/x509/server-cert.pem
      - ./server-key.pem:/etc/swanctl/private/server-key.pem
    restart: unless-stopped
